name: Deploy master & test builds

on:
  push:
    branches: [master, ci]

jobs:
  deploy:
    name: Deploy master tag image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/microbit-foundation/daplink:main .
      - name: Push tag to ghcr.io
        run: docker push ghcr.io/microbit-foundation/daplink:main

  build-daplink:
    name: Test build of DAPLink develop branch
    needs: deploy
    runs-on: ubuntu-latest
    container: ghcr.io/microbit-foundation/daplink:main
    steps:
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          python --version
          pip list
      - name: Clone DAPLink and checkout develop branch
        run: |
          git clone https://github.com/mbedmicro/DAPLink
          cd DAPLink
          git checkout -b develop origin/develop
      - name: Build DAPLink for kl27z_microbit_if
        run: python tools/progen_compile.py -t make_gcc_arm kl27z_microbit_if
