name: Deploy main tag & test it

on:
  push:
    branches: [main, ci]

jobs:
  deploy:
    name: Deploy main tag image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/microbit-foundation/daplink:main .
      - name: Push tag to ghcr.io
        run: docker push ghcr.io/microbit-foundation/daplink:main

  build-daplink:
    name: Build ${{ matrix.project }} ${{ matrix.build-system }} DAPLink, develop branch
    needs: deploy
    runs-on: ubuntu-latest
    container: ghcr.io/microbit-foundation/daplink:main
    strategy:
      fail-fast: false
      matrix:
        project:
          - kl26z_bl
          - kl26z_microbit_if
          - kl27z_microbit_bl
          - kl27z_microbit_if
          - nrf52820_microbit_bl
          - nrf52820_microbit_if
        build-system:
          - make_gcc_arm
          - cmake_gcc_arm -g ninja
    steps:
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          python --version
          pip list
      - name: Clone DAPLink and checkout develop branch
        run: |
          git clone https://github.com/mbedmicro/DAPLink
          cd DAPLink
          git checkout -b develop origin/develop
      - name: Build DAPLink for ${{ matrix.project }}
        working-directory: DAPLink
        run: python tools/progen_compile.py -t ${{ matrix.build-system }} ${{ matrix.project }}
